/**
 * Prints every labelled case as Markdown, so the labels can be reviewed without reading code.
 *   pnpm labels > docs/eval/labels.md
 */
import { EVAL_CASES, type Fact, type FieldGold } from "../src/lib/eval";
import { getTask } from "../src/lib/tasks";

const word = (k: string) => (k.startsWith("=") ? `${k.slice(1)} (whole word)` : k);
const alt = (a: string | string[]) =>
  Array.isArray(a) ? a.map(word).join(" + ") : word(a);
const facts = (fs: Fact[]) =>
  fs.map((f) => `${f.label} (${f.anyOf.map(alt).join(" | ")})`).join("; ");

function describe(g: FieldGold): string[] {
  if (g.kind === "enum") return [`must be: ${g.accept.join(" or ")}`];
  const out: string[] = [];
  if (g.kind === "list") {
    if (g.facts?.length) out.push(`must mention: ${facts(g.facts)}`);
    if (g.maxItems !== undefined) out.push(`at most ${g.maxItems} items`);
    if (g.count) out.push(`${g.count[0]} to ${g.count[1]} items`);
    if (g.forbidden?.length)
      out.push(`must not contain: ${g.forbidden.map(word).join(", ")}`);
    if (g.lowercase) out.push("all lowercase");
  } else {
    if (g.mentions?.length) out.push(`must mention: ${facts(g.mentions)}`);
    if (g.maxWords !== undefined) out.push(`at most ${g.maxWords} words`);
    if (g.sentences) out.push(`${g.sentences[0]} to ${g.sentences[1]} sentences`);
    if (g.language) out.push(`written in ${g.language}`);
  }
  return out;
}

console.log(`# Labelled cases

Generated by \`pnpm labels\`. **Status: labels written by an AI assistant and NOT yet reviewed by a human.**
Review them before trusting any accuracy number. See [../EVALUATION.md](../EVALUATION.md) for how they are used.

How to read a case: the input is what the model sees. Under it, one line per output field says what a
correct answer must satisfy. "must mention A (x | y)" means the field has to contain x or y. "a + b" means
both words in the same item. "(whole word)" means it must not be part of a longer word. Cases marked **ambiguous** accept more than one label and are reported separately.

If you disagree with a label, change it in \`src/lib/eval/cases-*.ts\`, then regenerate this file.
`);

let task = "";
for (const c of EVAL_CASES) {
  if (c.taskId !== task) {
    task = c.taskId;
    console.log(`\n## ${getTask(task)!.title} (\`${task}\`)\n`);
  }
  console.log(`### ${c.id}${c.ambiguous ? " (ambiguous)" : ""}\n`);
  console.log(`${c.note}\n`);
  if (c.ambiguous) console.log(`> Ambiguity: ${c.ambiguous}\n`);
  console.log("```text\n" + c.input + "\n```\n");
  console.log("| Field | Correct answer must satisfy |\n| --- | --- |");
  for (const [field, g] of Object.entries(c.gold))
    console.log(`| \`${field}\` | ${describe(g).join("; ")} |`);
  console.log("");
}
